# To see all available options, please visit the docs:
# https://docs.fossorial.io/Pangolin/Configuration/config

app:
    dashboard_url: "https://pangolin.nasflix.org"
    log_level: "info"

domains:
    domain1:
        base_domain: "nasflix.org"
        cert_resolver: "letsencrypt"
        prefer_wildcard_cert : true
    domain2:
        base_domain: "nasflix.local"

server:
    secret: "Gc0H1FuYaXL9gSZK2Z169IMOC5JD30Mv"
    cors:
        origins: ["https://pangolin.nasflix.org"]
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        allowed_headers: ["X-CSRF-Token", "Content-Type"]
        credentials: false

gerbil:
    start_port: 51820
    base_endpoint: "pangolin.nasflix.org"

orgs:
    block_size: 24
    subnet_group: 100.89.138.0/20



flags:
    require_email_verification: false
    disable_signup_without_invite: true
    disable_user_create_org: false
    allow_raw_resources: true
    enable_integration_api: true
    enable_clients: true